# .readthedocs.yml
# Read the Docs configuration file

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: FIDL/docs/conf.py

# Optionally build your docs in additional formats such as PDF and ePub
formats: all

# Optionally set the version of Python and requirements required to build your docs
python:
  version: 3
  install:
    - requirements: FIDL/docs/requirements.txt
    - requirements: requirements.txt
    - method: pip
      path: .
